### ISSUE TITLE
New release requested

### ISSUE THREAD

**Issue by blanxii** [rkazakov/ampify#12]
Hello,

Can you create a new release 0.2.7 and publish to npm please?

I think we add new features that should be published to the registry.

Thanks,

**Comment by rkazakov** [comment]
Hi @blanxii! Yes, sure. I was thinking to publishing minor update (0.3.0) as it's a larger update.

**Comment by rkazakov** [comment]
@blanxii Version `0.3.0` published. Please give it a go.
