### ISSUE TITLE
Request is async

### ISSUE THREAD

**Issue by gruberjl** [rkazakov/ampify#16]
request is asynchronous. It doesn't look like the code supports the promise properly. We'll need to convert to promises, async/await, or use a package like sync-request.

Let me know which you'd prefer and I'll send a pull request.

**Comment by rkazakov** [comment]
Good point, @gruberjl! How about using something like `axios` and promises?

**Comment by bkniffler** [comment]
I added a PR here: https://github.com/rkazakov/ampify/pull/21

**Comment by rkazakov** [comment]
Thanks for your contribution, @bkniffler!
Will you be able to use promises instead of async/await as we want to keep Node support prior to version 8?
Also can I ask you to add unit test coverage for your code please?
