### ISSUE TITLE
Require.js and Cheerio

### ISSUE THREAD

**Issue by karayeltasarim** [rkazakov/ampify#5]
Hi, it seems like you are doing a great work. I really like what i see but i couldn't make it work.

After i have downloaded the ampify, i have tried to work it as is, but it says require is not defined, so i assume that it needs require.js too.

After installing the require.js i have moved your index.js file to lib subfolder of the main directory and renamed it as ampify.js. Right after i have write your javascript sample to main.js as is:

```
const ampify = require('ampify');
const html = 'YOUR_HTML_CONTENT';
const amp = ampify(html, { cwd: 'amp' });

console.log(amp);
```

Still i am getting the following error:

> require.js:168 Uncaught Error: Module name "cheerio" has not been loaded yet for context: _. Use require([])

Any help would be amazing. Keep up the great work.

**Comment by rkazakov** [comment]
Hi @karayeltasarim,
No need for RequireJS.
If you using `ampify` with Node/Express, just create a `package.json`:
```js
{
  "name": "ampify-example",
  "main": "index.js",
  "dependencies": {
    "ampify": "^0.2.6",
    "express": "^4.16.1"
  }
}
```

Install dependencies:
```sh
npm install
```

Create a simple HTTP server in `index.js`:
```js
const ampify = require('ampify');
const express = require('express');

const app = express();

app.get('/', function (req, res) {
  const html = `
    <html>
      <head>
      <title>AMP page</title>
      </head>
      <body>
        <div>
          <p>This is text</p>
        </div>
      </body>
    </html>
  `;

  const amp = ampify(html, {cwd: 'amp'});

  res.send(amp); // Serving AMP HTML 
});

app.listen(3000, function () {
  console.log('Listening on port 3000!');
});
```

Run the server and see AMP HTML at http://localhost:3000/:
```sh
node index.js
```
