### ISSUE TITLE
sync-request usage

### ISSUE THREAD

**Issue by tapsboy** [rkazakov/ampify#7]
I see that index.js uses sync-request. Is there a specific reason why a sync request is used here instead of an async one?

**Comment by rkazakov** [comment]
Hi @tapsboy! No specific reason. It should be rewritten to use async version.

**Comment by knoxcard** [comment]
Hmmm....Chinese Rice

https://github.com/rkazakov/ampify/pull/11

**Comment by blanxii** [comment]
Can we close this @rkazakov ?
